Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "debian/bookworm64"
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
  end

  # Define two VMs with static private IP addresses.
  boxes = [
    { :name => "web",
      :ip => "192.168.57.21",
    },
    { :name => "log",
      :ip => "192.168.57.22",
    }
  ]

  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
    end
  end
  
  # Provision with Ansible for each machine
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/log.yml"  # Путь к общему playbook
    ansible.inventory_path = "provisioning/hosts.ini"  # Путь к инвентарному файлу
    ansible.become = true  # Если нужны привилегии суперпользователя
  end  
end
