---
- name: Создание сервиса по шаблону из файла
  template: 
    src: templates/service.j2
    dest: /etc/systemd/system/{{service_name}}
    mode: 0644

- name: Создание таймера по шаблону из файла
  template:
    src: templates/timer.j2
    dest: /etc/systemd/system/{{timer_name}}
    mode: 0644

- name: Запускаем таймер и включаем его
  systemd:
    name: "{{ timer_name }}"
    state: started
    enabled: true
    daemon_reload: true

- name: Запускаем первый раз резервное копирование, чтобы у таймера появился первый отсчет
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: true
...