---
- name: Install packages for spawn-fcgi
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop: "{{ spawn_fcgi_pkgs }}"

- name: Copy file fcgi.conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/spawn-fcgi/fcgi.conf"
    dest: /etc/spawn-fcgi/
    owner: root
    group: root
    mode: '0644'

- name: Copy file spawn-fcgi.service
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/systemd/system/spawn-fcgi.service"
    dest: /etc/systemd/system/spawn-fcgi.service
    owner: root
    group: root
    mode: '0644'

- name: Enable and start service spawn-fcgi.service
  ansible.builtin.service:
    name    : watchlog.timer
    state   : started
    enabled : yes
...