---
# - name: Remove default config
#   ansible.builtin.file:
#     path: /etc/nginx/conf.d/default.conf
#     state: absent

- name: Create new Nginx default config
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    backup: true
  notify:
    - Restart Nginx
...